XMLRPC:
  host: 0.0.0.0
  port: 5000
ZOOKEEPER:
  scheduler:
    hosts: 127.0.0.1:2181
COMMAND:
  - namekox_sqlalchemy.cli.subcmd.migration:Alembic
DATABASE:
  scheduler: mysql+pymysql://${MYSQL_USER:root}:${MYSQL_PASS:toor}@${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/scheduler_service?charset=utf8
APSCHEDULER:
  job_store_cfg:
    pool_pre_ping: true
  job_store_uri: mysql+pymysql://${MYSQL_USER:root}:${MYSQL_PASS:toor}@${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/scheduler_service?charset=utf8
