"""init

Revision ID: 53008ca8b6d8
Revises: 
Create Date: 2020-12-09 11:26:53.721022

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '53008ca8b6d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('job_state', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_jobs_next_run_time'), 'jobs', ['next_run_time'], unique=False)
    op.create_table('locks',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('logs',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ret_value', sa.Text(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_finished'), 'logs', ['finished'], unique=False)
    op.create_index(op.f('ix_logs_run_time'), 'logs', ['run_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_run_time'), table_name='logs')
    op.drop_index(op.f('ix_logs_finished'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('locks')
    op.drop_index(op.f('ix_jobs_next_run_time'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
